// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0m_DMKRmSiSXjmtUVP1SLzFLD2uWYfpQ',
    appId: '1:902991610927:web:06dda53267bc074b19f2da',
    messagingSenderId: '902991610927',
    projectId: 'odyssey-f9163',
    authDomain: 'odyssey-f9163.firebaseapp.com',
    databaseURL: 'https://odyssey-f9163-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'odyssey-f9163.appspot.com',
    measurementId: 'G-2CNDBG4G1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSIsmonmuU6teZDzxGEWGIpA56Htc-Rqc',
    appId: '1:902991610927:android:216f39f9f6464d1c19f2da',
    messagingSenderId: '902991610927',
    projectId: 'odyssey-f9163',
    databaseURL: 'https://odyssey-f9163-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'odyssey-f9163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohKZnjLL6f3P6uUtOwV9YkAyMe8R5ePA',
    appId: '1:902991610927:ios:7ad2a3a02363820219f2da',
    messagingSenderId: '902991610927',
    projectId: 'odyssey-f9163',
    databaseURL: 'https://odyssey-f9163-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'odyssey-f9163.appspot.com',
    iosClientId: '902991610927-tkqf804jtp80ivsdeq6hjf5vvr20ua2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCohKZnjLL6f3P6uUtOwV9YkAyMe8R5ePA',
    appId: '1:902991610927:ios:7ad2a3a02363820219f2da',
    messagingSenderId: '902991610927',
    projectId: 'odyssey-f9163',
    databaseURL: 'https://odyssey-f9163-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'odyssey-f9163.appspot.com',
    iosClientId: '902991610927-tkqf804jtp80ivsdeq6hjf5vvr20ua2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
